title: Produksi dan Luas Lahan Padi di Indonesia
subtitle: Data produksi, luas lahan, dan produktivitas padi dari
          berbagai Provinsi di Indonesia dari tahun 2018-2024

author:
  - name: Nurfian Qodar
    affiliations:
      - Universitas Siliwangi
date: 2025-03-07
# format: epub

